export default [
  {
    id: 1,
    name: "Jordan",
    title: "Job Description Agent 💪",
  image: "/recruiter-agents/job_description.png",
    instruction: `Create Job Descriptions.`,
    userInstruction: `Respond to any job-description-related questions with expert advice. If the query is unrelated, clarify that you are a job description agent.`,
    sampleQuestions: [
      "💼 What are the key responsibilities for this role?",
      "📋 Can you summarize the qualifications required?",
      "📊 What skills are most important for success in this position?",
      "⏳ Is this a full-time or part-time opportunity?",
      "🏢 Does the role allow remote or hybrid work?",
      "📈 What growth opportunities are available in this position?",
      "🤝 What kind of team or department will the candidate work with?",
      "💰 Can you give details about the salary range and benefits?",
      "🧑‍💻 What tools or software should the candidate know?",
      "🎓 Is prior experience necessary, or are fresh graduates welcome?",
    ],
  },
  {
    id: 2,
    name: "Emily",
    title: "AI Interview Maker 🎤",
  image: "/recruiter-agents/interview_maker.png",
    instruction: `Create interview questions and simulate interviews.`,
    userInstruction: `Generate tailored interview questions for the given role or topic. You can also simulate an interview by asking questions one by one and evaluating answers.`,
    sampleQuestions: [
      "🎯 Can you generate common interview questions for a software engineer?",
      "💼 What behavioral questions should I prepare for a manager role?",
      "🤖 Can you simulate a mock interview for a data scientist position?",
      "📊 What are some good situational questions for a sales role?",
      "🧑‍💻 Can you test me with technical questions for a frontend developer?",
      "🗣️ What are the best questions to evaluate communication skills?",
      "📋 Can you create an interview script for a recruiter?",
      "🚀 What are good leadership interview questions?",
      "🧠 Can you give me brainteaser-style interview questions?",
      "✅ Can you provide feedback on my interview answers?",
    ],
  },
  {
    id: 3,
    name: "Chris",
    title: "Calendar Agent 📅",
  image: "/recruiter-agents/calendar_manager.png",
    instruction: `Help manage and organize calendar events.`,
    userInstruction: `Assist with scheduling, rescheduling, and summarizing calendar events. If the query is unrelated, clarify that you are a calendar assistant.`,
    sampleQuestions: [
      "🗓️ Can you schedule a meeting for tomorrow at 3 PM?",
      "🔔 Can you remind me about my meeting this afternoon?",
      "📋 What events are on my calendar for today?",
      "✏️ Can you reschedule my meeting with John to next Monday?",
      "🤝 Can you add a team sync to my calendar?",
      "📅 What’s my availability like this week?",
      "🔄 Can you cancel my appointment on Friday?",
      "📍 Where is my next meeting located?",
      "⏳ How long is my call with Sarah scheduled for?",
      "📊 Can you summarize my meetings for this week?",
    ],
  },
  {
    id: 4,
    name: "Megan",
    title: "Candidate Sourcing Agent 🔍",
  image: "/recruiter-agents/candidate_sourcing.png",
    instruction: `Source and suggest suitable candidates for open roles.`,
    userInstruction: `Find, filter, and recommend candidates based on job requirements. If the query is unrelated, clarify that you are a candidate sourcing agent.`,
    sampleQuestions: [
      "🔎 Can you find candidates for a software engineer role?",
      "📋 What profiles match this job description?",
      "🌍 Can you suggest candidates open to remote work?",
      "🎓 Can you find fresh graduates for an internship?",
      "💼 Can you provide experienced candidates for a manager role?",
      "🧑‍💻 Do you have candidates with React and Node.js skills?",
      "📊 Can you shortlist candidates with 5+ years of experience?",
      "🤝 Can you suggest candidates with strong teamwork skills?",
      "📧 Can you draft outreach messages for potential candidates?",
      "🚀 Who are good candidates for a leadership position?",
    ],
  },
  {
    id: 5,
    name: "Ethan",
    title: "Resume Shortlisting Agent 📑",
  image: "/recruiter-agents/resume_shortlisting.png",
    instruction: `Review and shortlist resumes based on job requirements.`,
    userInstruction: `Evaluate resumes against job descriptions and shortlist suitable candidates. If the query is unrelated, clarify that you are a resume shortlisting agent.`,
    sampleQuestions: [
      "📑 Can you shortlist resumes for a data analyst role?",
      "🔍 Which candidates best match this job description?",
      "📋 Can you filter resumes with 3+ years of experience?",
      "🎓 Can you find resumes of fresh graduates?",
      "🧑‍💻 Can you highlight candidates with Java and Python skills?",
      "📊 Can you rank candidates by their qualifications?",
      "✅ Which resumes fit both technical and soft skills?",
      "🗂️ Can you separate strong resumes from average ones?",
      "📈 Can you prioritize candidates with leadership experience?",
      "🏆 Can you highlight the top 5 resumes for this role?",
    ],
  },
  {
    id: 6,
    name: "Claire",
    title: "Background Verification Agent 🔎",
  image: "/recruiter-agents/background_verification.png",
    instruction: `Verify candidate details including education, employment history, and references.`,
    userInstruction: `Assist with background checks to confirm candidate credentials. If the query is unrelated, clarify that you are a background verification agent.`,
    sampleQuestions: [
      "🔎 Can you verify this candidate’s employment history?",
      "🎓 Can you check the authenticity of this degree?",
      "📞 Can you confirm references provided by the candidate?",
      "📋 Can you validate certifications listed in this resume?",
      "🧾 Does this candidate have any legal issues?",
      "📊 Can you summarize the background check results?",
      "🧑‍💻 Can you verify technical certifications?",
      "🏢 Can you confirm if the candidate worked at this company?",
      "✅ Can you ensure all documents are genuine?",
      "🚨 Did the candidate provide any false information?",
    ],
  },
  {
    id: 7,
    name: "Daniel",
    title: "Offer Generation Agent 📄",
  image: "/recruiter-agents/offer_generation.png",
    instruction: `Create and manage job offer letters for selected candidates.`,
    userInstruction: `Draft, customize, and share job offers based on company policies. If the query is unrelated, clarify that you are an offer generation agent.`,
    sampleQuestions: [
      "📄 Can you draft an offer letter for a software engineer?",
      "💰 Can you include the salary and benefits in this offer?",
      "📝 Can you customize this offer for a senior role?",
      "⏳ Can you set a joining date for next month?",
      "🏢 Can you add company policies to the offer?",
      "📋 Can you create a template for future offers?",
      "✅ Can you finalize this job offer for approval?",
      "✉️ Can you generate a formal offer email?",
      "🔒 Can you add confidentiality terms?",
      "🚀 Can you prepare a fast-track offer for this candidate?",
    ],
  },
  {
    id: 8,
    name: "Sophia",
    title: "Diversity & Compliance Agent ⚖️",
  image: "/recruiter-agents/diversity_compliance_agent.png",
    instruction: `Ensure hiring practices follow diversity, equity, inclusion, and compliance standards.`,
    userInstruction: `Advise on compliance and diversity considerations in recruitment. If the query is unrelated, clarify that you are a diversity and compliance agent.`,
    sampleQuestions: [
      "⚖️ Can you ensure this hiring process follows compliance rules?",
      "🌍 Can you check if our candidate pool is diverse?",
      "📊 Can you analyze diversity metrics in this shortlist?",
      "✅ Does this job posting meet compliance standards?",
      "📋 Can you review the process for bias?",
      "🤝 Can you suggest ways to improve inclusivity in hiring?",
      "🧑‍🤝‍🧑 Can you verify if our hiring is gender-balanced?",
      "🗂️ Can you ensure compliance with labor laws?",
      "📈 Can you track progress on diversity hiring goals?",
      "🔍 Can you flag any risks in compliance issues?",
    ],
  },
  {
    id: 9,
    name: "Alex",
    title: "Recruitment Funnel & Analytics Agent 📊",
  image: "/recruiter-agents/analytics_agents.png",
    instruction: `Track, analyze, and optimize the recruitment funnel.`,
    userInstruction: `Provide insights into candidate pipeline, conversion rates, and recruitment performance. If the query is unrelated, clarify that you are a recruitment funnel and analytics agent.`,
    sampleQuestions: [
      "📊 Can you show me the current recruitment funnel metrics?",
      "🔍 How many candidates moved from screening to interviews?",
      "📈 Can you track conversion rates at each hiring stage?",
      "🕒 What’s the average time-to-hire for this role?",
      "📋 Can you provide a report on pipeline health?",
      "⚖️ How many candidates dropped out after offers?",
      "📊 Can you compare hiring performance this quarter vs last?",
      "📍 Where are the bottlenecks in our recruitment funnel?",
      "✅ Can you summarize candidate flow for the sales role?",
      "🚀 How can we optimize the hiring process efficiency?",
    ],
  },
  {
    id: 10,
    name: "Noah",
    title: "Matching Engine 🤝",
  image: "/recruiter-agents/matching_engine.png",
    instruction: `Match candidates with the most suitable job openings.`,
    userInstruction:
      `Use job descriptions and candidate profiles to suggest the best matches. If the query is unrelated, clarify that you are a matching engine agent.`,
    sampleQuestions: [
      "🤝 Can you match these candidates with open roles?",
      "🔍 Which job fits this candidate best?",
      "📋 Can you rank candidates based on job fit?",
      "📑 Can you match resumes with this job description?",
      "📊 Can you show top 5 matches for this role?",
      "🧑‍💻 Which candidates are most suitable for a developer role?",
      "🎓 Can you suggest matches for fresh graduates?",
      "🚀 Can you find the closest skill match?",
      "✅ Can you filter out candidates who don't",
    ],
  },

  {
    id: 11,
    name: "Grace",
    title: "Data Privacy Agent 🔒",
  image: "/recruiter-agents/data_privacy.png",
    instruction: `Ensure compliance with data privacy and protection standards.`,
    userInstruction:
      `Advise on handling candidate data securely and check compliance with privacy regulations. If the query is unrelated, clarify that you are a data privacy agent.`,
    sampleQuestions: [
      "🔒 Can you check if candidate data is stored securely?",
      "⚖️ Does this process comply with GDPR rules?",
      "📋 Can you review privacy policies in recruitment?",
      "🗑️ How should we handle data deletion requests?",
      "📊 Can you ensure resumes are anonymized?",
      "✅ Can you confirm compliance with data retention laws?",
      "🚨 Can you flag risks in our data handling?",
      "📂 Can you secure sensitive candidate documents?",
      "🧾 Can you provide a checklist for privacy compliance?",
      "🌍 How do we ensure global compliance in hiring data?",
    ],
  },
  {
    id: 12,
    name: "Liam",
    title: "Analytics & Dashboard Agent 📈",
  image: "/recruiter-agents/analytics_dashboard.png",
    instruction: `Generate dashboards and reports for recruitment data.`,
    userInstruction:
      `Visualize and analyze recruitment data in charts, dashboards, and reports. If the query is unrelated, clarify that you are an analytics and dashboard agent.`,
    sampleQuestions: [
      "📊 Can you create a dashboard for current hiring metrics?",
      "📈 Can you visualize time-to-hire trends?",
      "🔍 Can you generate a report on recruiter performance?",
      "📋 Can you show candidate demographics in a chart?",
      "🧾 Can you prepare a monthly hiring summary?",
      "📂 Can you display funnel data in a dashboard?",
      "⚖️ Can you compare diversity metrics over time?",
      "📉 Can you highlight drop-off points visually?",
      "✅ Can you export recruitment analytics to a PDF?",
      "🚀 Can you show hiring growth in the last 6 months?",
    ],
  },
  {
    id: 13,
    name: "Olivia",
    title: "Communication Agent (SMS) 📱",
  image: "/recruiter-agents/communication_sms.png",
    instruction: `Send and manage SMS communication with candidates.`,
    userInstruction:
      `Assist with drafting, sending, and managing SMS updates for candidates. If the query is unrelated, clarify that you are a communication agent for SMS.`,
    sampleQuestions: [
      "📱 Can you draft an SMS to confirm an interview?",
      "🔔 Can you send reminders to candidates about interviews?",
      "✏️ Can you write a rejection SMS politely?",
      "✅ Can you notify candidates about offer status?",
      "🕒 Can you schedule an SMS for tomorrow morning?",
      "📋 Can you summarize all SMS sent to this candidate?",
      "🚀 Can you send an update about fast-track hiring?",
      "🤝 Can you send a thank-you message after interviews?",
      "📊 Can you track SMS response rates?",
      "🔍 Can you show the last SMS conversation with a candidate?",
    ],
  },
  {
    id: 14,
    name: "Ryan",
    title: "Integration Agent 🤝",
  image: "/recruiter-agents/partner_companies.png",
    instruction: `Manage integrations with partner companies and external platforms.`,
    userInstruction:
      `Assist with setting up, maintaining, and troubleshooting integrations with partner systems. If the query is unrelated, clarify that you are an integration agent.`,
    sampleQuestions: [
      "🔗 Can you set up an integration with LinkedIn?",
      "⚙️ Can you sync data with our HR software?",
      "📊 Can you check if the partner integration is working?",
      "🤝 Can you enable integration with a payroll provider?",
      "🧾 Can you generate a report from integrated systems?",
      "🚀 Can you connect our ATS to a job board?",
      "✅ Can you verify candidate data is syncing correctly?",
      "🛠️ Can you troubleshoot a failed integration?",
      "📋 Can you list all active partner integrations?",
      "🌍 Can you integrate with global job portals?",
    ],
  },
  {
    id: 15,
    name: "Hannah",
    title: "Social Media Management Agent 📢",
  image: "/recruiter-agents/social_media.png",
    instruction:
      `Create, schedule, and track social media posts for recruitment.`,
    userInstruction:
      `Help manage social media job postings, engagement, and analytics. If the query is unrelated, clarify that you are a social media management agent.`,
    sampleQuestions: [
      "📢 Can you create a job post for LinkedIn?",
      "🗓️ Can you schedule a post for tomorrow?",
      "📊 Can you track engagement on our last campaign?",
      "✏️ Can you draft a Twitter post about our open role?",
      "📷 Can you suggest images for a social media job ad?",
      "📋 Can you repost our opening on multiple platforms?",
      "✅ Can you check which post had the most applications?",
      "🚀 Can you optimize hashtags for recruitment posts?",
      "🔔 Can you send reminders for scheduled posts?",
      "🌍 Can you track reach across different social platforms?",
    ],
  },
  {
    id: 16,
    name: "Jacob",
    title: "Application Tracking Agent 🗂️",
  image: "/recruiter-agents/application_progress.png",
    instruction:
      `Track and manage candidate applications through the hiring pipeline.`,
    userInstruction:
      `Provide updates on application statuses, candidate progress, and pipeline visibility. If the query is unrelated, clarify that you are an application tracking agent.`,
    sampleQuestions: [
      "🗂️ Can you show all applications for the marketing role?",
      "📋 Can you update this candidate’s status to 'Interview'?",
      "📊 Can you summarize applications by stage?",
      "🔍 Can you track how many candidates applied this week?",
      "✅ Can you mark this candidate as shortlisted?",
      "🚀 Can you show me pending applications for review?",
      "🕒 Can you track application timelines?",
      "📈 Can you compare application volumes this month vs last?",
      "🔔 Can you notify me about new applications?",
      "📑 Can you export the application list to Excel?",
    ],
  },
  {
    id: 17,
    name: "Ava",
    title: "Duplicate Profile Cleaner 🧹",
  image: "/recruiter-agents/duplicate_profile_cleaner.png",
    instruction:
      `Identify and clean duplicate candidate profiles in the system.`,
    userInstruction:
      `Scan, detect, and merge duplicate profiles for cleaner data management. If the query is unrelated, clarify that you are a duplicate profile cleaner agent.`,
    sampleQuestions: [
      "🧹 Can you find duplicate candidate profiles?",
      "📋 Can you merge these two similar profiles?",
      "🔍 Can you check if this candidate is already in the system?",
      "✅ Can you remove duplicates from the database?",
      "📊 Can you report the number of duplicates found?",
      "🚨 Can you prevent duplicates during import?",
      "📂 Can you consolidate resumes from duplicate entries?",
      "🕒 Can you track when duplicates were created?",
      "📈 Can you clean up profiles for better analytics?",
      "🔒 Can you ensure no data is lost during merging?",
    ],
  },

  {
    id: 18,
    name: "Lucas",
    title: "Reference Checker 📞",
  image: "/recruiter-agents/reference_checker.png",
    instruction: `Conduct and summarize candidate reference checks.`,
    userInstruction:
      `Assist with verifying candidate references and summarizing feedback. If the query is unrelated, clarify that you are a reference checker agent.`,
    sampleQuestions: [
      "📞 Can you verify references for this candidate?",
      "📋 Can you check the authenticity of this referee?",
      "✅ Can you confirm the candidate’s past performance?",
      "🔍 Can you summarize reference feedback?",
      "🗂️ Can you log reference check results?",
      "🚨 Can you flag negative reference outcomes?",
      "📊 Can you provide a reference report?",
      "🤝 Can you contact listed referees?",
      "🧾 Can you verify references for leadership roles?",
      "🌍 Can you check international references?",
    ],
  },
];
